FROM library/postgres:latest

WORKDIR /var/lib/postgres

RUN chown postgres /var/lib/postgres/

USER postgres

RUN initdb --pgdata=/var/lib/postgres/andfeedback -E 'UTF-8' --lc-collate='en_US.UTF-8' --lc-ctype='en_US.UTF-8'
